#--------------------------------
#GitHub Actions Basics
#--------------------------------
name: My-GitHubActions-Basics

env: 
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"
on: 
  push:
    branches: 
      - main

jobs:
 my_testing:
   runs-on: ubuntu-latest
   steps:
   - name: Print Hello Message
     run : echo "Hello World from Testing job"
     
   - name: Execute few commands
     run : |
      echo "Hello Message1"
      echo "Hello Message2"
      echo "Application name: ${{ env.APPLICATION_NAME }}"
      
   - name: Lista current folder
     run : ls -la
    
    
 my_deploy:
   runs-on: ubuntu-latest
   needs: [my_testing]
   steps:
   - name: Print Hello Message
     run : echo "Hello World from Deploy job"
     
   - name: Printing Deploiment package
     run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
