#--------------------------------
#GitHub Actions Basics
#--------------------------------
name: My-GitHubActions-Basics

env: 
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"
on: 
  push:
    branches: 
      - main

jobs:
 my_testing:
   runs-on: ubuntu-latest
   steps:
   - name: Print Hello Message
     run : echo "Hello World from Testing job"
     
   - name: Execute few commands
     run : |
      echo "Hello Message1"
      echo "Hello Message2"
      echo "Application name: ${{ env.APPLICATION_NAME }}"

   - name: Lista current folder
     run : ls -la
          
   - name: Git clone my repo
     uses: actions/checkout@v1
      
   - name: Lista current folder
     run : ls -la
    
    
 my_deploy:
   runs-on: ubuntu-latest
   needs: [my_testing]
   env:
    VAR1 : "This is job level Variable1"
    VAR2 : "This is job level Variable2"
    
   steps:
   - name: Print Hello Message
     run : echo "Hello World from Deploy job"
     
   - name: Print env vars
     run : | 
       echo " Var1 = ${{ env.VAR1 }}
       echo " Var2 = ${{ env.VAR2 }}
       echo " Var3 = $LOCAL_VAR
     env:
        LOKAL_VAR: "This is Supper local Environment variable"
        
   - name: Printing Deploiment package
     run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
     
   - name: Lets test some packages 1
     run : aws --version
     
   - name: Lets test some packages 2
     run : zip --version
