#--------------------------------
#GitHub Actions Basics
#--------------------------------
name: My-GitHubActions-Basics

on: 
  push:
    branches: 
      - main

jobs:
 my_testing:
    runs-on: ubuntu latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from testingjob"
    
    
 my_deploy:
    runs-on: ubuntu-latest
    
     steps:
     - name: Print Hello Message
       run : echo "Hello World from Deploy job"
